"""Shared contracts for the agentic M2 literature pipeline.

Feature branches should import public contracts from this module instead of
depending on another tool's private implementation.
"""

from .adapter import AgenticM2Adapter, AgenticM2Module
from .models import (
    ContentLevel,
    CoverageReport,
    DocumentChunk,
    DocumentRecord,
    EvidenceBucket,
    EvidenceChunk,
    EvidenceLinkedKnowledge,
    FulltextStatus,
    PaperReadingResult,
    PaperRecord,
    QueryIntent,
    RemainingSearchBudget,
    ScoutNote,
    SearchBudget,
    SearchQuery,
    SearchRunResult,
    SearchState,
    StopReason,
)
from .export import build_m2_knowledge_export_run
from .protocols import (
    CoverageEvaluatorProtocol,
    DocumentParserProtocol,
    EvidenceRetrieverProtocol,
    FulltextResolverProtocol,
    LiteratureSourceProtocol,
    PaperDeduplicatorProtocol,
    PaperRankerProtocol,
    PaperReaderProtocol,
    QueryPlannerProtocol,
    ReadingExtractionWorkflowProtocol,
    ScoutReaderProtocol,
)
from .search import (
    CoverageEvaluator,
    IterativeSearchAgent,
    PaperDeduplicator,
    PaperRanker,
    ScoutReader,
)
from .reading import (
    BioCDocumentParser,
    FullTextReadingWorkflow,
    HybridEvidenceRetriever,
    InMemoryChunkStore,
    PMCFulltextResolver,
    QwenPaperReader,
)

__all__ = [
    "AgenticM2Adapter",
    "AgenticM2Module",
    "ContentLevel",
    "CoverageEvaluator",
    "CoverageEvaluatorProtocol",
    "CoverageReport",
    "DocumentChunk",
    "DocumentParserProtocol",
    "DocumentRecord",
    "EvidenceBucket",
    "EvidenceChunk",
    "EvidenceLinkedKnowledge",
    "EvidenceRetrieverProtocol",
    "FulltextResolverProtocol",
    "FulltextStatus",
    "FullTextReadingWorkflow",
    "HybridEvidenceRetriever",
    "InMemoryChunkStore",
    "IterativeSearchAgent",
    "LiteratureSourceProtocol",
    "PaperDeduplicator",
    "PaperDeduplicatorProtocol",
    "PaperRanker",
    "PaperRankerProtocol",
    "PaperReaderProtocol",
    "PaperReadingResult",
    "PaperRecord",
    "PMCFulltextResolver",
    "QueryIntent",
    "QueryPlannerProtocol",
    "QwenPaperReader",
    "ReadingExtractionWorkflowProtocol",
    "RemainingSearchBudget",
    "ScoutNote",
    "ScoutReader",
    "ScoutReaderProtocol",
    "SearchBudget",
    "SearchQuery",
    "SearchRunResult",
    "SearchState",
    "StopReason",
    "BioCDocumentParser",
    "build_m2_knowledge_export_run",
]
